### ISSUE TITLE
Push: GCM Canonical IDs

### ISSUE THREAD

**Issue by flovilmart** [parse-community/parse-server-push-adapter#12] opened 2016-04-04 02:08 UTC
(originally posed on https://github.com/ParsePlatform/parse-server/issues/966 by @Dynogic)
Hi there,

I noticed that the GCM Push does not support canonical IDs yet. https://developers.google.com/cloud-messaging/registration#canonical-ids

Any idea to when it'll be implemented? Its very scary pushing current code into production when there could be possibilities of duplicate messages or complete push notification failure (the latter being a rare event where Google decides to change registration IDs. Quote from GCM docs: "If the registration token expires (for example, Google might decide to refresh registration tokens, or the APNS token has expired for iOS devices).")

Thanks,
Jake.

**Comment by adirgan** [comment] 2016-06-09 14:34
Describe your issue in as much detail as possible.

I have a problem with the parse server with respect to the installations, I have an application with many users, each time the user is authenticated by another server, I have a query that checks in a class if the user already exists, if there is the creates, and creates a pointer from the installation of the device until the user who believe in the user class, that in order to define which user sent him push, when I close my session, what I do is delete the object point in the installations, thus not reach him more push to that device that does not have associated any user, I have a serious problem about that, when the application's uninstall without closing session and reinstalling happens that continues to reach the push, the strange thing is that when I had this system in Parse.com never passed this, because when you uninstall the application and the previous installations was not associated with that device, therefore we did not reach the push when you desinstalabas the application and not borrabas the object pointer to that user installations.

do not know if this is a mistake or something happened to them, that should not be working well.

Steps to reproduce

Please include a detailed list of steps that reproduce the issue. Include curl commands when applicable.

create a pointer from the installation to another class with a specific user
uninstall the application, without erasing the installation pointer
application installed again without creating new pointer to the user in the other class
send a push to the user that is pointing to the installation
Expected Results

what should happen is that as uninstall the application installation I stay in class pointing the user should be outdated and therefore not send push the device that had that obsolete installation

Actual Outcome

It is reaching the push of a previous installation, so if you install and uninstall the application 10 times, and 10 times not delete the pointer of the installation before uninstalling, sending a push users will reach 10 times the notification by the 10 installations that were in the class of installations

Environment Setup

Server

parse-server version: 2.2.11
Operating System: Ubuntu 14.04 LTS
Hardware: VPS
Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): Codero
Database

MongoDB version: 3.0.6
Storage engine: Mongo
Hardware: VPS
Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): Codero



I have this problem and post it on parse server, but I think it is concerning this.

**Closed** 2022-03-30 21:39 UTC
