### ISSUE TITLE
[error]: Certificate and key do not match 

### ISSUE THREAD

**Issue by burhanyilmaz** [parse-community/parse-server-push-adapter#179] opened 2020-10-28 23:26 UTC
When I run the parse server, throw this error `Certificate and key do not match `.

When the passphrase is true, throw this error `Certificate and key do not match `
When the passphrase is false, there is no error. it is so strange. 

How can solve this? Thanks.

My config here that
```
  push: {
    android: {
      apiKey: process.env.FCM_SERVER_KEY,
      senderId: ''
    },
    ios: [
      {
        production: false,
        topic: 'com.my.app',
        pfx: './assets/pushNotifications/myapp.p12',
        passphrase: 'pass'
      },
      {
        production: false,
        topic: 'com.my.app',
        pfx: './assets/pushNotifications/myapp2.p12',
        passphrase: 'pass'
      }
    ]
  }
```

**Comment by TomWFox** [comment] 2020-10-29 20:15
Duplicate of https://github.com/parse-community/parse-server/issues/6978

**Closed** 2020-10-29 20:15 UTC
